In [5]:
# https://datascienceschool.net/01%20python/03.02%20%EB%B0%B0%EC%97%B4%EC%9D%98%20%EC%83%9D%EC%84%B1%EA%B3%BC%20%EB%B3%80%ED%98%95.html

In [1]:
import numpy as np

In [8]:
x=np.array([1,2,3])
x.dtype

dtype('int32')

In [10]:
x=np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [11]:
x=np.array([1,2,3.0])
x.dtype

dtype('float64')

In [12]:
x=np.array([1,2,3], dtype='U')
x.dtype

dtype('<U1')

In [13]:
x[0]+x[1]

'12'

# Inf와 NaN

In [14]:
np.array([0,1,-1,0])/np.array([1,0,0,0])

C:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [15]:
np.log(0)

C:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [16]:
np.exp(-np.inf)

0.0

# 배열생성

In [17]:
# 크기가 정해져 있고 모든 값이 0인 배열을 생성하려면 zeros 명령을 사용한다. 인수로는 배열을 크기를 뜻하는 정수를 넣는다.
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [18]:
#크기를 뜻하는 튜플을 입력하면 다차원 배열도 만들수 있다.
b=np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#array와 마찬가지로 dtype 인수를 명시하면 해당 자료형 원소를 가진 배열을 만든다.
c=np.zeros((5,2), dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [20]:
#문자열 배열도 가능하지면 모든 원소의 문자열 크기가 같아야 한다. 만약 더 큰 크기의 문자열을 할당하면 잘릴 수 있다.
d=np.zeros(5, dtype='U')
d

array(['', '', '', '', ''], dtype='<U1')

In [21]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['a', 'a', 'A', '', ''], dtype='<U1')

In [26]:
#0이 아닌 1로 초기화된 배열을 생성하려면 ones 명령을 사용한다.
e=np.ones((2,3,4),dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [27]:
#만약 크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 생성하고 싶다면 ones_like, zeros_like 명령을 사용한다.
f=np.ones_like(b,dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [28]:
#배열의 크기가 커지면 배열을 초기화하는데도 시간이 걸린다. 
#이 시간을 단축하려면 배열을 생성만 하고 특정한 값으로 초기화를 하지 않는 empty 명령을 사용할 수 있다.
#empty 명령으로 생성된 배열에는 기존에 메모리에 저장되어 있던 값이 있으므로 배열의 원소의 값을 미리 알 수 없다.
g=np.empty((4,3))
g

array([[1.14490487e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.87821632e+180],
       [5.78732753e+174, 1.10657252e-046, 1.31311321e-071],
       [1.00105171e+165, 9.14185170e+169, 2.23417822e-052]])

In [29]:
#arange 명령은 NumPy 버전의 range 명령이라고 볼 수 있다. 특정한 규칙에 따라 증가하는 수열을 만든다.
np.arange(10) #0..n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(3,21,2) #시작, 끝(포함하지않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [31]:
#linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0,100,5) #시작,끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [32]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

# 전치연산

In [2]:
# 2차원 배열의 전치(transpose) 연산은 행과 열을 바꾸는 작업이다.
#이는 배열의 T 속성으로 구할 수 있다. 메서드가 아닌 속성이라는 점에 유의 한다.
A=np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# 배열의 크기 변형

In [17]:
# 일단 만들어진 배열의 내부 데이터는 보존한 채로 형태만 바꾸려면 reshape 명령이나 메서드를 사용한다.
# 예를 들어 12개의 원소를 가진 1차원 행렬은 3x4 형태의 2차원 행렬로 만들 수 있다.
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
#사용하는 원소의 갯수가 정해저 있기 때문에 reshape 명령의 형태 튜플의 원소 중 하나는 -1이라는 숫자로 대체할 수 있다. 
#-1을 넣으면 해당 숫자는 다를 값에서 계산되어 사용된다.
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [21]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [22]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
#다차원 배열을 무조건 1차원으로 만들기 위해서는 flatten 나 ravel 메서드를 사용한다.
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
#배열 사용에서 주의할 점은 길이가 5인 1차원 배열과 행, 
#열의 갯수가 (5,1)인 2차원 배열 또는 행, 
#열의 갯수가 (1, 5)인 2차원 배열은 데이터가 같아도 엄연히 다른 객체라는 점이다.
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [27]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [28]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [30]:
#이렇게 같은 배열에 대해 차원만 1차원 증가시키는 경우에는 newaxis 명령을 사용하기도 한다.
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [32]:
#hstack 명령은 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 만든다.
#연결할 배열은 하나의 리스트에 담아야 한다.
a1=np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
a2=np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [36]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [38]:
#vstack 명령은 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열을 만든다.
#연결할 배열은 마찬가지로 하나의 리스트에 담아야 한다.
b1=np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
b2=np.zeros((4,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
#dstack 명령은 제3의 축 즉, 행이나 열이 아닌 깊이(depth) 방향으로 배열을 합친다. 
#가장 안쪽의 원소의 차원이 증가한다. 즉 가장 내부의 숫자 원소가 배열이 된다. 
#shape 정보로 보자면 가장 끝에 값이 2인 차원이 추가되는 것이다.
#이 예제의 경우에는 shape 변화가 2개의 (3 x 4) -> 1개의 (3 x 4 x 2)가 된다.
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
c2=np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [45]:
np.dstack([c1,c2]).shape

(3, 4, 2)

In [46]:
#stack 명령은 dstack의 기능을 확장한 것으로 dstack처럼 마지막 차원으로 연결하는 것이 아니라 사용자가 지정한 차원(축으로) 배열을 연결한다. 
#axis 인수(디폴트 0)를 사용하여 연결후의 회전 방향을 정한다. 
#디폴트 인수값은 0이고 가장 앞쪽에 차원이 생성된다. 즉, 배열 두 개가 겹치게 되므로 연결하고자 하는 배열들의 크기가 모두 같아야 한다.
#다음 예에서는 axis=0 이므로 가장 바깥에 값이 2인 차원이 추가된다. 즉, shape 변화는 2개의 (3 x 4) -> 1개의 (2 x 3 x 4) 이다..
c=np.stack([c1,c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [47]:
c.shape

(2, 3, 4)

In [48]:
c=np.stack([c1,c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [49]:
c.shape

(3, 2, 4)